WebApplication1/WebApplication1/Controllers/MapController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using Mushrooms.Models;
using Newtonsoft.Json;
using Microsoft.EntityFrameworkCore;

namespace Mushrooms.Controllers
{
    [Authorize]
    public class MapController : Controller
    {
        private ApplicationDbContext db;
        public MapController(ApplicationDbContext Db)
        {
             db=Db;

        }
        public IActionResult Index()
        {
           
            var listofMarkers = new List<MarkerViewModel>();
            var placesFromDatabase = db.Places.Include("Report").ToList();
            foreach( var item in placesFromDatabase)
            {
                var ob = new MarkerViewModel
                {
                    lat = item.lat,
                    lng = item.lng,
                    info = item.Report.Description

                };
                listofMarkers.Add(ob);

            }

            string json = JsonConvert.SerializeObject(listofMarkers);
            ViewBag.Markers = json;

            return View();
        }
    }
}

WebApplication1/WebApplication1/Controllers/ReportsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Mushrooms.Models;
using WebApplication1.Models;

namespace Mushrooms.Controllers
{
    [Authorize]
    public class ReportsController : Controller
    {
        private ApplicationDbContext db;
        private UserManager<AppUser> userManager;
        private SignInManager<AppUser> singInManager;
        private readonly IHostingEnvironment hostingEnvironment;


        public ReportsController(UserManager<AppUser> userManage, 
            ApplicationDbContext DatabaseContext, SignInManager<AppUser> ap, 
            IHostingEnvironment hosting)
        {
            singInManager = ap;
            db = DatabaseContext;
            userManager = userManage;
            this.hostingEnvironment = hosting;

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> CreateReport(ReportViewModel report)
        {
            var userName = HttpContext.User.Identity.Name;
            try
            {
                if(!(report.Vivodeship.Count()).Equals(1))
                {
                    ModelState.AddModelError("", "Wybierz województwo");
                }
                if (ModelState.IsValid)
                {
                    string uniqueFileName = null;
                    //photo upload
                    if(report.Photo != null)
                    {
                       string folderwithUploads = Path.Combine(hostingEnvironment.WebRootPath, "images");
                       uniqueFileName = Guid.NewGuid().ToString() + "_" + report.Photo.FileName;
                       string filePath = Path.Combine(folderwithUploads, uniqueFileName);
                       report.Photo.CopyTo(new FileStream(filePath, FileMode.Create));
                        
                    }
                    

                    var context = HttpContext.User.Claims;
        
                    var user = db.Users.Include("AcheivementUsers").FirstOrDefault(x => x.Username == userName);
                    var chosenVivodeship = report.Vivodeship[0];
                    var reportNew = new Report
                    {
                        Date = DateTime.Now,
                        Description = report.Description,
                        Title = report.Title,
                        Vivodeship = chosenVivodeship,
                        FieldAccepted = report.FieldAccepted,
                        User =user,
                        photoPath = uniqueFileName 
                        
                    };

                    db.Reports.Add(reportNew);
                    var placeNew = new Place
                    {
                        lat = report.lat,
                        lng = report.lng,
                        Report = reportNew

                    };
                    db.Places.Add(placeNew);
                    await db.SaveChangesAsync();
                    var countedR= db.Reports.Select(x => x).
                        Where(x => x.UserId == user.UserId).ToList().Count();
        
                    if(countedR.Equals(1))
                    {
                        var ko = db.Acheivements.Select(x => x).Where(x => x.Name == "Nowicjusz").ToList();
                        var koCounted = ko.Count();
                        if (koCounted.Equals(0))
                        {
                            var newTitle = new Acheivement
                            {
                                Name = "Nowicjusz"
                            };
                            db.Acheivements.Add(newTitle);
                            await db.SaveChangesAsync();
                        }
                        var koP = db.Acheivements.Select(x => x).Where(x => x.Name == "Nowicjusz").ToList();
                        var IdAchievement = koP[0].Id;
                        var userId = user.UserId;
                        var newAchive = new AcheivementUser
                        {
                            UserId =userId,
                            AcheivementId=IdAchievement
                        };

                        user.AcheivementUsers.Add(newAchive);
                        await db.SaveChangesAsync();
                    }
                    if (countedR.Equals(10))
                    {
                        var ko = db.Acheivements.Select(x => x).Where(x => x.Name == "Nowicjusz").ToList();
                        var koCounted = ko.Count();
                        if (koCounted.Equals(0))
                        {
                            var newTitle = new Acheivement
                            {
                                Name = "Znawca"
                            };
                            db.Acheivements.Add(newTitle);
                            await db.SaveChangesAsync();
                        }
                        var koP = db.Acheivements.Select(x => x).Where(x => x.Name == "Nowicjusz").ToList();
                        var IdAchievement = koP[0].Id;
                        var userId = user.UserId;
                        var newAchive = new AcheivementUser
                        {
                            UserId = userId,
                            AcheivementId = IdAchievement
                        };

                        user.AcheivementUsers.Add(newAchive);
                        await db.SaveChangesAsync();
                    }

                    return RedirectToAction(nameof(Index));
                }
            }
            catch (DbUpdateException /* ex */)
            {
                //Log the error (uncomment ex variable name and write a log.
                ModelState.AddModelError("", "Unable to save changes. " +
                    "Try again, and if the problem persists " +
                    "see your system administrator.");
            }


            return RedirectToAction("Index");

        }
        [HttpGet]
        public IActionResult CreateReport()
        {
            var viewModelPass = new ReportViewModel();
            viewModelPass.Vivodeship = new List<string>
            {
                 "dolnośląskie",
                 "kujawsko-pomorskie",
                 "lubelskie",
                 "lubuskie",
                 "łódzkie",
                 "małopolskie",
                 "mazowieckie",
                 "opolskie",
                 "podkarpackie",
                 "podlaskie",
                 "pomorskie",
                 "śląskie",
                 "świętokrzyskie",
                 "warmińsko-mazurskie",
                 "wielkopolskie",
                 "zachodniopomorskie",

            };

            return View(viewModelPass);
        }
        public IActionResult Index()
        {
            var Vivodeship = new List<string>
            {
                 "dolnośląskie",
                 "kujawsko-pomorskie",
                 "lubelskie",
                 "lubuskie",
                 "łódzkie",
                 "małopolskie",
                 "mazowieckie",
                 "opolskie",
                 "podkarpackie",
                 "podlaskie",
                 "pomorskie",
                 "śląskie",
                 "świętokrzyskie",
                 "warmińsko-mazurskie",
                 "wielkopolskie",
                 "zachodniopomorskie",

            };
            ViewBag.Vivo = Vivodeship;

            var xd = User.Identity.Name;
            var user = HttpContext.User.Identity.Name;
            var reportsNow = db.Reports.Include("User").OrderByDescending(x => x.Date).ToList();
            return View(reportsNow);
        }
        public IActionResult SortByVivodeship(string vivodeship)
        {
            var user = HttpContext.User.Identity.Name;
            var reportsNow = db.Reports.Include("User").Where(x => x.Vivodeship == vivodeship).OrderByDescending(x => x.Date).ToList();

            return View(reportsNow);
        }
    }
}

WebApplication1/WebApplication1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Mushrooms</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/fontawesome.min.css">
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.min.css">

</head>
@using Microsoft.AspNetCore.Identity
@inject SignInManager<AppUser> SignInManager
@inject UserManager<AppUser> UserManager
<body>
    <header>
        @if (SignInManager.IsSignedIn(User))
        {
            <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
                <div class="container">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Mushrooms</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Reports" asp-action="Index">Raporty</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Map" asp-action="Index">Mapa</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Statistics" asp-action="Index">Statystyki</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Index">Profil</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Prywatność</a>
                            </li>
                        </ul>
                    </div>
                    <div class="topnav-right">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                            <li class="nav-item">
                                <a class="nav-link text-dark"> Witaj @User.Identity.Name!</a>
                            </li>
                            <li>
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Logout">
                                Wyloguj się
                                <i class="fa fa-sign-out-alt"></i>
                            </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
        }
        else
        {
            <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
                <div class="container">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Mushrooms</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                       
                    </div>
                    <div class="topnav-right">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Identity" asp-controller="Account" asp-action="Login">
                                    Zaloguj się
                                    <i class="fa fa-sign-in-alt"></i>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Identity" asp-controller="Account" asp-action="Register">
                                    Zarejestruj się
                                    <i class="fa fa-registered"></i>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
        }
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - Mushrooms - <a asp-area="" asp-controller="Home" asp-action="Privacy">Prywatność</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>